apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-gc
  labels:
    app.kubernetes.io/component: controller
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: aa3813a8
data:
  _example: {{ .Values.configGc.Example | toYaml | indent 1 }}