apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-knative-serving-aggregated-addressable-resolver
  labels:
  {{- include "knative-serving-core.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: "true"
rules: null