apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-routing-serving-certs
  labels:
    networking.knative.dev/certificate-type: system-internal
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
spec:
  dnsNames:
  - kn-routing
  - data-plane.knative.dev
  secretName: routing-serving-certs