apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "knative-kourier.fullname" . }}-3scale-kourier-gateway-pdb
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.3ScaleKourierGatewayPdb.minAvailable }}
  maxUnavailable: {{ .Values.3ScaleKourierGatewayPdb.maxUnavailable }}
  selector:
    matchLabels:
      app: 3scale-kourier-gateway
    {{- include "knative-kourier.selectorLabels" . | nindent 6 }}