apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-kourier.fullname" . }}-net-kourier-controller
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.netKourierController.type }}
  selector:
    app: net-kourier-controller
  {{- include "knative-kourier.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.netKourierController.ports | toYaml | nindent 2 }}