apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-knative-serving-istio
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/controller: "true"
  {{- include "knative-net-istio.labels" . | nindent 4 }}
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - gateways
  - destinationrules
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch