apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-net-istio-webhook-certs
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "knative-net-istio.labels" . | nindent 4 }}