autoscalerHpa:
  autoscalerHpa:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    env:
      configLoggingName: config-logging
      configObservabilityName: config-observability
      metricsDomain: knative.dev/serving
    image:
      repository: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa@sha256
      tag: 22dd4098eba2e4cc7c77c9b805fe286790b45ee45097d70809ae2345397ad898
    resources:
      limits:
        cpu: 300m
        memory: 400Mi
      requests:
        cpu: 30m
        memory: 40Mi
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  type: ClusterIP
kubernetesClusterDomain: cluster.local
