apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "knative-istio.fullname" . }}-d
  labels:
    app: istiod
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - watch
  - list
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - update
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "knative-istio.fullname" . }}-d
  labels:
    app: istiod
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "knative-istio.fullname" . }}-d'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-istio.fullname" . }}-d'
  namespace: '{{ .Release.Namespace }}'