apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-istio.fullname" . }}-istio
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
data:
  mesh: {{ .Values.istio.mesh | toYaml | indent 1 }}
  meshNetworks: {{ .Values.istio.meshNetworks | quote }}