apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-config.webhook.istio.networking.internal.knative.dev
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "knative-net-istio.fullname" . }}-
  labels:
  {{- include "knative-net-istio.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "knative-net-istio.fullname" . }}-net-istio-webhook'
      namespace: '{{ .Release.Namespace }}'
  failurePolicy: Fail
  name: config.webhook.istio.networking.internal.knative.dev
  objectSelector:
    matchLabels:
      app.kubernetes.io/component: net-istio
      app.kubernetes.io/name: knative-serving
  sideEffects: None