apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-config-istio
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "knative-net-istio.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configIstio.Example | toYaml | indent 1 }}