apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-knative-local-gateway
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "knative-net-istio.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 8081
      protocol: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-net-istio.fullname" . }}-knative-local-gateway
  labels:
    app.kubernetes.io/component: net-istio
    experimental.istio.io/disable-gateway-port-translation: "true"
    networking.knative.dev/ingress-provider: istio
  {{- include "knative-net-istio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.knativeLocalGateway.type }}
  selector:
    istio: ingressgateway
  {{- include "knative-net-istio.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.knativeLocalGateway.ports | toYaml | nindent 2 }}