apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "knative-kourier.fullname" . }}-3scale-kourier-gateway
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 3scale-kourier-gateway