apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-kourier.fullname" . }}-config-kourier
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configKourier.Example | toYaml | indent 1 }}