apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-kourier.fullname" . }}-net-kourier-controller
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.netKourierController.replicas }}
  selector:
    matchLabels:
      app: net-kourier-controller
    {{- include "knative-kourier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: net-kourier-controller
      {{- include "knative-kourier.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - env:
        - name: CERTS_SECRET_NAMESPACE
          value: {{ quote .Values.netKourierController.controller.env.certsSecretNamespace
            }}
        - name: CERTS_SECRET_NAME
          value: {{ quote .Values.netKourierController.controller.env.certsSecretName }}
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METRICS_DOMAIN
          value: {{ quote .Values.netKourierController.controller.env.metricsDomain }}
        - name: KOURIER_GATEWAY_NAMESPACE
          value: {{ quote .Values.netKourierController.controller.env.kourierGatewayNamespace
            }}
        - name: ENABLE_SECRET_INFORMER_FILTERING_BY_CERT_UID
          value: {{ quote .Values.netKourierController.controller.env.enableSecretInformerFilteringByCertUid
            }}
        - name: KUBE_API_BURST
          value: {{ quote .Values.netKourierController.controller.env.kubeApiBurst }}
        - name: KUBE_API_QPS
          value: {{ quote .Values.netKourierController.controller.env.kubeApiQps }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.netKourierController.controller.image.repository }}:{{ .Values.netKourierController.controller.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 6
          grpc:
            port: 18000
            service: null
          periodSeconds: 10
        name: controller
        ports:
        - containerPort: 18000
          name: http2-xds
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 18000
            service: null
          periodSeconds: 10
        resources: {{- toYaml .Values.netKourierController.controller.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.netKourierController.controller.containerSecurityContext
          | nindent 10 }}
      restartPolicy: Always
      serviceAccountName: {{ include "knative-kourier.fullname" . }}-net-kourier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-kourier.fullname" . }}-3scale-kourier-gateway
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: 3scale-kourier-gateway
    {{- include "knative-kourier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: 3scale-kourier-gateway
      {{- include "knative-kourier.selectorLabels" . | nindent 8 }}
      annotations:
        networking.knative.dev/poke: v0.26
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args: {{- toYaml .Values.3ScaleKourierGateway.kourierGateway.args | nindent 8 }}
        command:
        - /usr/local/bin/envoy
        env:
        - name: DRAIN_TIME_SECONDS
          value: {{ quote .Values.3ScaleKourierGateway.kourierGateway.env.drainTimeSeconds
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.3ScaleKourierGateway.kourierGateway.image.repository }}:{{ .Values.3ScaleKourierGateway.kourierGateway.image.tag
          | default .Chart.AppVersion }}
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X POST http://localhost:9901/drain_listeners?graceful; sleep $DRAIN_TIME_SECONDS
        livenessProbe:
          failureThreshold: 6
          httpGet:
            httpHeaders:
            - name: Host
              value: internalkourier
            path: /ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        name: kourier-gateway
        ports:
        - containerPort: 8080
          name: http2-external
          protocol: TCP
        - containerPort: 8081
          name: http2-internal
          protocol: TCP
        - containerPort: 8443
          name: https-external
          protocol: TCP
        - containerPort: 8090
          name: http-probe
          protocol: TCP
        - containerPort: 9443
          name: https-probe
          protocol: TCP
        - containerPort: 9000
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: internalkourier
            path: /ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        resources: {{- toYaml .Values.3ScaleKourierGateway.kourierGateway.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.3ScaleKourierGateway.kourierGateway.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/config
          name: config-volume
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: {{ include "knative-kourier.fullname" . }}-kourier-bootstrap
        name: config-volume