apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-kourier.fullname" . }}-kourier-internal
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kourierInternal.type }}
  selector:
    app: 3scale-kourier-gateway
  {{- include "knative-kourier.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.kourierInternal.ports | toYaml | nindent 2 }}