apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-kourier.fullname" . }}-net-kourier
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - networking.internal.knative.dev
  resources:
  - ingresses/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-kourier.fullname" . }}-net-kourier
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-kourier.fullname" . }}-net-kourier'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-kourier.fullname" . }}-net-kourier'
  namespace: '{{ .Release.Namespace }}'