apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-kourier.fullname" . }}-net-kourier
  labels:
    app.kubernetes.io/component: net-kourier
    networking.knative.dev/ingress-provider: kourier
  {{- include "knative-kourier.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.netKourier.serviceAccount.annotations | nindent 4 }}