apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-activator-service
  labels:
    app: activator
    app.kubernetes.io/component: activator
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.activatorService.type }}
  selector:
    app: activator
  {{- include "knative-serving-core.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.activatorService.ports | toYaml | nindent 2 }}