apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-leader-election
  labels:
    app.kubernetes.io/component: controller
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: f4b71f57
data:
  _example: {{ .Values.configLeaderElection.Example | toYaml | indent 1 }}