apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-deployment
  labels:
    app.kubernetes.io/component: controller
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 720ddb97
data:
  _example: {{ .Values.configDeployment.Example | toYaml | indent 1 }}
  queue-sidecar-image: {{ .Values.configDeployment.queueSidecarImage | quote }}