apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/component: observability
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 54abd711
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}