apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-autoscaler
  labels:
    app.kubernetes.io/component: autoscaler
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 47c2487f
data:
  _example: {{ .Values.configAutoscaler.Example | toYaml | indent 1 }}