apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-activator
  labels:
    app.kubernetes.io/component: activator
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: activator
      role: activator
    {{- include "knative-serving-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: activator
        app.kubernetes.io/component: activator
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.15.2
        role: activator
      {{- include "knative-serving-core.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: activator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: GOGC
          value: {{ quote .Values.activator.activator.env.gogc }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.activator.activator.env.configLoggingName }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.activator.activator.env.configObservabilityName }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.activator.activator.env.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.activator.activator.image.repository }}:{{ .Values.activator.activator.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 12
          httpGet:
            port: 8012
          initialDelaySeconds: 15
          periodSeconds: 10
        name: activator
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8012
          name: http1
        - containerPort: 8013
          name: h2c
        readinessProbe:
          failureThreshold: 5
          httpGet:
            port: 8012
          periodSeconds: 5
        resources: {{- toYaml .Values.activator.activator.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.activator.activator.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "knative-serving-core.fullname" . }}-activator
      terminationGracePeriodSeconds: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-autoscaler
  labels:
    app.kubernetes.io/component: autoscaler
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaler.replicas }}
  selector:
    matchLabels:
      app: autoscaler
    {{- include "knative-serving-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: autoscaler
        app.kubernetes.io/component: autoscaler
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.15.2
      {{- include "knative-serving-core.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: autoscaler
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.autoscaler.autoscaler.env.configLoggingName }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.autoscaler.autoscaler.env.configObservabilityName }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.autoscaler.autoscaler.env.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.autoscaler.autoscaler.image.repository }}:{{ .Values.autoscaler.autoscaler.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            port: 8080
        name: autoscaler
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8080
          name: websocket
        readinessProbe:
          httpGet:
            port: 8080
        resources: {{- toYaml .Values.autoscaler.autoscaler.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.autoscaler.autoscaler.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "knative-serving-core.fullname" . }}-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: controller
    {{- include "knative-serving-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.15.2
      {{- include "knative-serving-core.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: controller
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.controller.controller.env.configLoggingName }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.controller.controller.env.configObservabilityName }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.controller.controller.env.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controller.controller.image.repository }}:{{ .Values.controller.controller.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: probes
            scheme: HTTP
          periodSeconds: 5
        name: controller
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8080
          name: probes
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: probes
            scheme: HTTP
          periodSeconds: 5
        resources: {{- toYaml .Values.controller.controller.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.controller.controller.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "knative-serving-core.fullname" . }}-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: webhook
      role: webhook
    {{- include "knative-serving-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.15.2
        role: webhook
      {{- include "knative-serving-core.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: webhook
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: {{ quote .Values.webhook.webhook.env.configLoggingName }}
        - name: CONFIG_OBSERVABILITY_NAME
          value: {{ quote .Values.webhook.webhook.env.configObservabilityName }}
        - name: WEBHOOK_NAME
          value: {{ quote .Values.webhook.webhook.env.webhookName }}
        - name: WEBHOOK_PORT
          value: {{ quote .Values.webhook.webhook.env.webhookPort }}
        - name: METRICS_DOMAIN
          value: {{ quote .Values.webhook.webhook.env.metricsDomain }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.webhook.webhook.image.repository }}:{{ .Values.webhook.webhook.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        name: webhook
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8443
          name: https-webhook
        readinessProbe:
          httpGet:
            port: 8443
            scheme: HTTPS
          periodSeconds: 1
        resources: {{- toYaml .Values.webhook.webhook.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.webhook.webhook.containerSecurityContext |
          nindent 10 }}
      serviceAccountName: {{ include "knative-serving-core.fullname" . }}-controller
      terminationGracePeriodSeconds: 300