apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-knative-serving-podspecable-binding
  labels:
    duck.knative.dev/podspecable: "true"
  {{- include "knative-serving-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - configurations
  - services
  verbs:
  - list
  - watch
  - patch