apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-activator
  labels:
    app.kubernetes.io/component: activator
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.activator.serviceAccount.annotations | nindent 4 }}