apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-webhook
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    role: webhook
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    app: webhook
    role: webhook
  {{- include "knative-serving-core.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.ports | toYaml | nindent 2 }}