apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "knative-istio.fullname" . }}-ingressgateway
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.ingressgateway.minAvailable }}
  maxUnavailable: {{ .Values.ingressgateway.maxUnavailable }}
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
    {{- include "knative-istio.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-istio.fullname" . }}-ingressgateway
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingressgateway.type }}
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  {{- include "knative-istio.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ingressgateway.ports | toYaml | nindent 2 }}