apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-istio.fullname" . }}-ingressgateway-service-account
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingressgatewayServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-istio.fullname" . }}-reader-service-account
  labels:
    app: istio-reader
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.readerServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-istio.fullname" . }}-d
  labels:
    app: istiod
    release: istio
  {{- include "knative-istio.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.d.serviceAccount.annotations | nindent 4 }}