configIstio:
  Example: |-
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################
    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
    # external-gateways defines a gateway and Istio service to serve external traffic.
    # It is the new and preferred way to define the configuration.
    # The format is as follow:
    # ```
    # external-gateways: |
    #   - name: {{gateway_name}}
    #     namespace: {{gateway_namespace}}
    #     service: {{ingress_name}}.{{ingress_namespace}}.svc.cluster.local
    #     labelSelector:
    #       matchExpressions:
    #       - key: {{label_key}}
    #         operator: {{operator}}
    #         values: [{{label_value}}]
    #       matchLabels:
    #         {{label_key}}: {{label_value}}
    # ```
    # name, namespace & service are mandatory and can't be empty. labelSelector is optional.
    # If labelSelector is specified, the external gateway will be used by the knative service with matching labels.
    # See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for more details about labelSelector.
    # Only one external gateway can be specified without a selector. It will act as the default external gateway.
    external-gateways: |
      - name: knative-ingress-gateway
        namespace: knative-serving
        service: istio-ingressgateway.istio-system.svc.cluster.local
    #
    #
    # The old format has the following pattern:
    # ```
    # gateway.{{gateway_namespace}}.{{gateway_name}}: "{{ingress_name}}.{{ingress_namespace}}.svc.cluster.local"
    # ```
    # Please use the new configuration format `external-gateways` for future compatibility.
    # This configuration will raise an error if either `external-gateways` or `local-gateways` is defined.
    gateway.knative-serving.knative-ingress-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
    # local-gateways defines a cluster local gateway to allow pods outside of the mesh to access
    # Services and Routes not exposing through an ingress. If the users
    # do have a service mesh setup, this isn't required and can be removed.
    #
    # An example use case is when users want to use Istio without any
    # sidecar injection (like Knative's istio-ci-no-mesh.yaml). Since every pod
    # is outside of the service mesh in that case, a cluster-local service
    # will need to be exposed to a cluster-local gateway to be accessible.
    #
    # It is the new and preferred way to define the configuration.
    # The format is as follow:
    # ```
    # local-gateways: |
    #   - name: {{local_gateway_name}}
    #     namespace: {{local_gateway_namespace}}
    #     service: {{cluster_local_gateway_name}}.{{cluster_local_gateway_namespace}}.svc.cluster.local
    #     labelSelector:
    #       matchExpressions:
    #       - key: {{label_key}}
    #         operator: {{operator}}
    #         values: [{{label_value}}]
    #       matchLabels:
    #         {{label_key}}: {{label_value}}
    # ```
    # name, namespace & service are mandatory and can't be empty. labelSelector is optional.
    # If labelSelector is specified, the local gateway will be used by the knative service with matching labels.
    # See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for more details about labelSelector.
    # Only one local gateway can be specified without a selector. It will act as the default local gateway.
    local-gateways: |
      - name: knative-local-gateway
        namespace: knative-serving
        service: knative-local-gateway.istio-system.svc.cluster.local
    #
    #
    # The old format has the following pattern:
    # ```
    # local-gateway.{{local_gateway_namespace}}.{{local_gateway_name}}:
    # "{{cluster_local_gateway_name}}.{{cluster_local_gateway_namespace}}.svc.cluster.local"
    # ```
    # Please use the new configuration format `local-gateways` for future compatibility.
    # This configuration will raise an error if either `external-gateways` or `local-gateways` is defined.
    local-gateway.knative-serving.knative-local-gateway: "knative-local-gateway.istio-system.svc.cluster.local"
knativeLocalGateway:
  ports:
  - name: http2
    port: 80
    targetPort: 8081
  - name: https
    port: 443
    targetPort: 8444
  type: ClusterIP
kubernetesClusterDomain: cluster.local
netIstioController:
  controller:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    env:
      configLoggingName: config-logging
      configObservabilityName: config-observability
      enableSecretInformerFilteringByCertUid: "false"
      metricsDomain: knative.dev/net-istio
    image:
      repository: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256
      tag: 3c8d9cba61bbdf91d2c0ddc15ce7593ee776cbf5f7b4262132e0b2230441e16b
    resources:
      limits:
        cpu: 300m
        memory: 400Mi
      requests:
        cpu: 30m
        memory: 40Mi
netIstioWebhook:
  ports:
  - name: http-metrics
    port: 9090
    targetPort: metrics
  - name: http-profiling
    port: 8008
    targetPort: profiling
  - name: https-webhook
    port: 443
    targetPort: https-webhook
  type: ClusterIP
  webhook:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    env:
      configLoggingName: config-logging
      configObservabilityName: config-observability
      metricsDomain: knative.dev/net-istio
      webhookName: net-istio-webhook
      webhookPort: "8443"
    image:
      repository: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256
      tag: fc70f9b07cc855e39357bbc5166e933074473e10ecf01d78ee289f6b8c968890
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 20Mi
